### ISSUE TITLE
undefined method `tc_profile_url'

### ISSUE THREAD

**Issue by rrodrigu3z** [instructure/lti_tool_provider_example#2]
Hi, 
I'm new with LTI and have been playing with this TP example but I'm getting the following error:

```
NoMethodError (undefined method `tc_profile_url' for #<IMS::LTI::Models::Messages::BasicLTILaunchRequest:0x007f85e82bbdd8>):
  ims-lti (2.0.0.beta.41) lib/ims/lti/models/messages/message.rb:178:in `method_missing'
  ims-lti (2.0.0.beta.41) lib/ims/lti/services/tool_proxy_registration_service.rb:11:in `tool_consumer_profile'
  /Users/rrodriguez/.rvm/gems/ruby-2.1.6@lti/bundler/gems/rails_lti2_provider-42ea6bad1c94/lib/rails_lti2_provider/tool_proxy_registration.rb:12:in `initialize'
  /Users/rrodriguez/.rvm/gems/ruby-2.1.6@lti/bundler/gems/rails_lti2_provider-42ea6bad1c94/lib/rails_lti2_provider/controller_helpers.rb:19:in `new'
  /Users/rrodriguez/.rvm/gems/ruby-2.1.6@lti/bundler/gems/rails_lti2_provider-42ea6bad1c94/lib/rails_lti2_provider/controller_helpers.rb:19:in `registration_request'
  activesupport (4.1.6) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.6) lib/active_support/callbacks.rb:143:in `call'
```

I have tried with lti_tool_consumer_example as consumer and the [IMS LTI Tool Consumer emulator](http://ltiapps.net/test/tc.php). I'm using the `/register` endpoint.

Looks like it is some method missing in the ims-lti gem.

Any ideas?

Thanks!

**Comment by SoxFace** [comment]
I'm getting the same error. Using the following repos and http://localhost:3000/register as the Provider launch url being submitted to the consumer tool. Any ideas on fixing the error?

- https://github.com/instructure/lti_tool_provider_example
- https://github.com/instructure/lti_tool_consumer_example

**Comment by adnankasif** [comment]
I am getting the same error too

**Comment by rgigger** [comment]
same
